# Site settings
title: Thomas Lam
email: thomas@lamcw.com
description: >
  Thomas Lam's personal website
url: "https://lamcw.com"
analytics_id: UA-93493353-1
author: lamcw
twitter:
  username: lamcw
  card: summary
github_username: lamcw
logo:
  /assets/img/icon/favicon.ico
social:
  name: Thomas Lam
  links:
    - https://twitter.com/lamcw
    - https://github.com/lamcw
    - https://www.linkedin.com/in/thomaslamcw

# Where things are
collections:
  posts:
    output:   true
sass:
  sass_dir: _sass
  style: compressed
include: ["_pages"]
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

permalink: pretty
paginate: 5
paginate_path: "/archive/page:num/"

kramdown:
  auto_ids:       true
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  blanklines: false
  startings: [html, head, body]

plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji
